### PR TITLE
External HYPRE

### PR DESCRIPTION
**Pull request by aprilnovak**
I think these are the changes needed to use an external HYPRE. I'm doing some further testing to make sure, but wanted to put this here to discuss.

### CODE REVIEW

**Comment by stgeke** [comment]
Can you please confirm that this works as expected using the latest next branch?

**Comment by aprilnovak** [comment]
Through some very good luck, I actually think this works now - I think I stumbled on the correct CMake command to get things to work for me.

Full disclaimer: I am not an expert in CMake. These changes work for us, but I'm not well versed in what impacts this could have on NekRS by itself.

**Comment by stgeke** [comment]
If we push https://github.com/stgeke/nekRS/issues/494 on top of this PR (no big deal to add) we can remove the `HYPRE_INSTALL_DIR` option. In this case we simply always use the HYPRE version we ship. Conflicts with other projects can no longer happen.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/nekRS/commit/9ae887200454a3409e8a0c324bde9989815716c3

**Pull request closed without merging**
