### PR TITLE
[WIP] Adding AMGX to build system

### PR DESCRIPTION
**Pull request by RonRahaman**
This introduces the AMGX source code and some initial support in the build system.  

The AMGX v2.2.0 source was added as a git subtree from https://github.com/NVIDIA/AMGX/releases/tag/v2.2.0.  There are some issues in the AMGX CMakeLists that prevent it from being used as a subproject (such as using `CMAKE_SOURCE_DIR` instead of `CMAKE_CURRENT_SOURCE_DIR`).  I've raised an issue about it on the repo (https://github.com/NVIDIA/AMGX/issues/147).  In the meantime, I put the necessary changes in our subtree.

In the nekRS CMakeLists, AMGX is enabled via the `-DENABLE_AMGX` option.  I noticed that you need to include the AMGX header paths explicitly.  Looks like, in the AMGX CMakeLists, the library targets don't propagate the include paths.

You should also check on `nekrs.cpp` and `main.cpp`.  I added some header includes and function calls as I was writing the code to see if it compiled properly.

I'm having trouble compliling branch of nekRS it for unrelated reasons (`ulong` seems to be defined wrong when I build), so this PR is untested.  However, I thought it might provide you with a good start.  Please let me know if you have any problems with it.

### CODE REVIEW

**Comment by stgeke** [comment]
Build seems to fail when using latest version of https://github.com/Nek5000/nekRS/pull/297

**Comment by MalachiTimothyPhillips** [comment]
For me, this required building with `-fPIC`. In addition, I was getting various linker errors to cublas/cusparse, as well amgx_template, amgx_eigensolver.

I attempted adding the following to nekRS/CMakeLists.txt:

```
  find_library_local_first(cublas_library cublas "The cuBLAS CUDA library")
  find_library_local_first(cusparse_library cusparse "The cusparse CUDA library")
  find_library_local_first(cusolver_library cusolver "The cusolver CUDA library")
  target_link_libraries(nekrs-lib PUBLIC amgx_core amgx_base amgx_template_plugin amgx_eigensolvers ${cublas_library} ${cusparse_library} ${cusolver_library})
```

However, it now looks as if I'm having an issue with building the amgx unit tests:
```
/home/malachi2/develop/nekRS/3rd_party/AMGX/tests/src/unit_test.cu:28:10: fatal error: testframework.h: No such file or directory
 #include "testframework.h"
```

**Comment by RonRahaman** [comment]
Thanks, I'll pull from upstream and take a look.  I think the missing `testframework.h` might be another problem with the relative paths in AMGX's CMakeLists.

**Comment by stgeke** [comment]
To save time we should only build what we really need (target amgxsh).

**Comment by RonRahaman** [comment]
I see that libamgxsh is built as a shared library, whereas libamgx is explicitly built as static.  If we're only linking to libamgxsh, then that might take care of the PIC issue.  
 
https://github.com/NVIDIA/AMGX/blob/77f91a94c05edbf58349bad447bbface7207c2b4/CMakeLists.txt#L359-L360

**Comment by RonRahaman** [comment]
The newest update does this
* Uses AMGX's CMakeLists before OCCA's.  This correctly sets `CUDA_NVCC_FLAGS` to compile with PIC
* Omits the AMGX eigensolvers, tests, and examples from the build
* Hardcodes compute capability 7 and 8 for AMGX build in makenrs
* Reverts the temporary changes to `main.cpp` and `nekrs.hpp`
* Omits `set_property(GLOBAL PROPERTY RULE_MESSAGES OFF)` from nekRS's CMakeLists.  Since the AMGX objects take so long to compile, I find the compilation messages are very helpful.  Without the messages, it just appears as if the build is stalling.  The fetch content and install messages are still supressed, since those are still fast.

**Pull request merged**
