### PR TITLE
Enable residual projection for block solver

### PR DESCRIPTION
**Pull request by MalachiTimothyPhillips**
I think there's a bug in the block solver case that I'm still tracking down.

### CODE REVIEW

**Comment by MalachiTimothyPhillips** [comment]
Okay, this should be ready for review. The bug was in ellipticSolve.cpp. Before hand, we had only saved `elliptic->Ntotal * sizeof(dfloat)` before using the projection code. Changing this to save `elliptic->Ntotal * elliptic->Nfields * sizeof(dfloat)` fixed the issue. I added the velocity block solver + solution projection to the ethier CI test-case and updated the expected number of velocity solver iterations.

**Comment by MalachiTimothyPhillips** [comment]
One additional change: I need to change the occurrences of `m` with `numVecsProjection`. I'll add this presently.

**Comment by MalachiTimothyPhillips** [comment]
Closes #157

**Comment by stgeke** [comment]
Can you please merge this PR into master.

**Pull request merged**
