### PR TITLE
Add link to documentation

### PR DESCRIPTION
**Pull request by aprilnovak**
Now that we've hosted the website publicly, tell non-dev people that it exists.

### CODE REVIEW

**Comment by aprilnovak** [comment]
@stgeke, would it be worthwhile to merge this? While the documentation is far from complete, it might help some users and cut down on the Discussions traffic. Also, providing the link should encourage more people to perhaps contribute.

**Comment by stgeke** [comment]
The documentation needs a careful review + a fair amount of corrections. Unfortunately I don't have the time to do this.

**Comment by aprilnovak** [comment]
will you have time in the future to review it?

**Comment by lcarasik** [comment]
Documentation is needed for users.

**Comment by stgeke** [comment]
Added in https://github.com/Nek5000/nekRS/commit/756e744b0314914244fc9385f61ae6e6e4406285.
Currently it shows just a dummy. Can you please copy your repo content to doc (directory in this repo).

**Comment by stgeke** [comment]
Closing for now. 
@aprilnovak Please open a new PR whenever you think you're ready.

**Pull request closed without merging**
