### PR TITLE
Use 32-bit for HYPRE_Real by default

### PR DESCRIPTION
**Pull request by RonRahaman**

### CODE REVIEW

**Comment by stgeke** [comment]
Please change it to be OFF by default.

**Comment by RonRahaman** [comment]
Sorry for the misunderstanding.  OFF is the default in HYPRE:

https://github.com/hypre-space/hypre/blob/fbe25305a7f37e978546a0bac51da725537892ad/src/CMakeLists.txt#L42

So if that's what you want, we won't need to update anything in NekRS.

**Comment by stgeke** [comment]
It should be explicitly defined as OFF even though it's the default.

**Comment by RonRahaman** [comment]
So do you want to define the cache variable in hypre.cmake using the `FORCE` option?

**Pull request merged**
