### PR TITLE
HYPRE v2.21.0 update

### PR DESCRIPTION
**Pull request by RonRahaman**
Updates HYPRE subtree to v2.21.0.

I made sure to omit these from the subtree update, since we had deleted them ourselves

* 3rd_party/hypre/src/test
* 3rd_party/hypre/src/docs
* 3rd_party/hypre/src/examples
* 3rd_party/hypre/src/utilities/version 

And I did it in such a way that I didn’t re-add them to the history and them remove them again.  So we shouldn’t have those directories as an extraneous part of the history

### CODE REVIEW

**Comment by stgeke** [comment]
Why does this PR touch so many files?

**Comment by RonRahaman** [comment]
It's a subtree update

**Comment by stgeke** [comment]
Can you please merge into next instead of semfem.

**Comment by stgeke** [comment]
Let's wait until HYPRE supports a runtime switch for running on CPU or GPU.

**Pull request closed without merging**
