### PR TITLE
[WIP] High-level documentation for the input files

### PR DESCRIPTION
**Pull request by aprilnovak**
This is the first of many documentation PRs transferring from the [nekRSDoc repo](https://github.com/aprilnovak/nekRSDoc) to the nekRS repo. The reason I am splitting these into separate PRs is because with every page, there are 20+ outstanding questions/things that remain to be completed, and doing it all in one PR would be very difficult to keep track of everything.

This PR adds a home page, a glossary, and a page describing the basics of the nekRS input files. 

After this PR is approved, I will continue and add the other documentation pages in manageable chunks.

### CODE REVIEW

**Comment by aprilnovak** [comment]
FYI you can build this documentation (before it's merged) by checking out this branch locally and running `make html` in `nekRS/doc`, then opening `nekRS/doc/build/html/index.html` in a web browser. The required dependencies are described in the [README for the original doc repo](https://github.com/aprilnovak/nekRSDoc).

**Comment by yslan** [comment]
Lots of details to go through. I'd like to discuss the style and format first. 

1. I suggest to change the ordering of the listed keys in par file. 
    The alphabetic order is good for dictionary which assumes user already knows the name of the keys.
    In that case, a webpage search will also do the work for them.

    For example, user may find it difficult to look through all stopping criteria since they are 
scattered at many places such as `stopAt`, `numSteps`, `elapsedTime` and `endTime`.
    It'd be nice to at least be sorted with dependency.

    Also, is there anyway to sort the list via some priority? 
Some keys will probably never be used at all, such as `galerkinCoarseOperator`. 

2. In the `.udf` section, function should be sorted by the called order.  

3. I think using tables would be nice. 
    Like this:     https://nek5000.github.io/NekDoc/problem_setup/case_files.html#parameter-file-par

4. I suggest to use table + bulletin.
    This will also help distinguish the header/sub-header/section/subsection. 
    Using only the font size in a long page can easily get lost. 

5. Not sure if we want to let the users know the existence of the `.co2` and the `.usr` files
    If there is a "transition from Nek5000 to NekRS page", then it's probably better to hide them at here.

Thanks!

**Comment by aprilnovak** [comment]
> It'd be nice to at least be sorted with dependency.
> Also, is there anyway to sort the list via some priority?

I think what I would propose is to leave the list alphabetical, but maybe change font color/use separate tables for "advanced" parameters. What do you think?

> I think using tables would be nice.

I agree with this - at the time I just couldn't figure out how to get the text to wrap the right way, but now that I see the Nek5000 example I can copy that.

> I suggest to use table + bulletin.

What is a bulletin? There is a "taskbar" at the left side of the page - did you mean something else?

> If there is a "transition from Nek5000 to NekRS page", then it's probably better to hide them at here.

This is a good idea - and no, I didn't have anything like that written up yet. A few things from this page could be moved to a page like that.

**Comment by yslan** [comment]
Still vote against the alphabetic order : )
For example, if you open one of the par file, you'd expect the keys are grouped in the way you want to handle. 

That's just my opinion.

```
[GENERAL]
#verbose = true
polynomialOrder = 7
#startFrom = "restart.fld"
stopAt = endTime
endTime = 200

dt = 6.0e-3
timeStepper = tombo2
extrapolation = subCycling
subCyclingSteps = 2

writeControl = runTime
writeInterval = 1

filtering = hpfrt
filterWeight = 0.1/${dt}
filterModes = 1
```





> What is a bulletin? 

Sorry, I mean Bullet, or even separation line will help. (Maybe tables might be enough.)
The boundary between sections/sub-sections is not very clear. Plus, it's a long page.

Task bar is good for an one-way search. For example `.par` -> `PRESSURE` -> `smootherType`. It's not telling what section you are at from `smootherType`, and you will still get lost next time. 

Sure, I can see the "PRESSURE section" has slightly larger font, but it's not very clear since we are at many depth levels. Especially, it mixed the code-insert-block.

**Comment by aprilnovak** [comment]
> separation line will help. (Maybe tables might be enough.)

I'll see what I can do to make the sections clearer - I agree, the font sizes in the rst headings don't differ as much as I'd like between section levels.

> Still vote against the alphabetic order : )

How do other people feel about this? I'm okay with grouping terms, I just want the grouping to be meaningful and not run into the cases where we might have one-off keys that don't group well with other things that we have separate tables/etc. for.

**Comment by aprilnovak** [comment]
What do you guys think of the table formatting so far? It is a *huge* pain to do tables in rst, so I want to get the green light on the content (i.e. the presence of the four columns I have in each table) before I go through and do tables for everything else.

**Comment by stgeke** [comment]
This PR seems to be inactive. Closing it for now.

**Pull request closed without merging**
