### PR TITLE
Patch the file read to fix a hang

### PR DESCRIPTION
**Pull request by thilinarmtb**

### CODE REVIEW

**Comment by stgeke** [comment]
Could you please provide an explanation of what the bug was?

**Comment by stgeke** [comment]
I noticed that the current implementation might read an additional empty line at the end due to how the loop is structured. To enhance readability and ensure that this issue is avoided, could you please use e.g. `while (std::getline(fudf, text))` instead of a for loop? I believe this approach reads more naturally and improves code clarity.

**Comment by thilinarmtb** [comment]
> Could you please provide an explanation of what the bug was?

With the current state, NekRS keeps printing `<<<` during some NekNek runs.

**Comment by thilinarmtb** [comment]
> I noticed that the current implementation might read an additional empty line at the end due to how the loop is structured. To enhance readability and ensure that this issue is avoided, could you please use e.g. `while (std::getline(fudf, text))` instead of a for loop? I believe this approach reads more naturally and improves code clarity.

`for (std::string text; std::getline(fudf, text))` is identical to `while (std::getline(fudf, text))` 
except restricting  the scope of the variable `text`.

**Pull request closed without merging**
