### PR TITLE
Small fix to get a consistent finalTime if interval not evenly divisible by dt

### PR DESCRIPTION
**Pull request by aprilnovak**
If the user-specified time interval (`finalTime - startTime`) is not perfectly divisible by the specified `dt`, then the current approach is to add one time step such that we simulate just slightly past the user-desired final time.

We make this adjustment to `NtimeSteps`, but in doing so, the `ins->finalTime` becomes incorrect (it holds the un-adjusted final time).

**Example**: User sets `dt=0.1`, `finalTime=0.42`. We would adjust the number of time steps to be 5, but our final time would still be 0.42. This PR makes sure that the final time is 0.5.

We need this from the Cardinal end because MOOSE controls the end of its timestepping based on `finalTime` - it consistently converts whatever combinations of dt/steps/end_time set by the user so that this number is indicative of any possible setup. nekRS should behave the same, or else we cannot guarantee control of the timestepping correctly.

### CODE REVIEW

**Comment by stgeke** [comment]
Yes finalTime doesn't match exactly but I modifying the user input finalTime is also not a good idea. The best "fix" is to implement https://github.com/Nek5000/nekRS/issues/21.

**Comment by aprilnovak** [comment]
Sure, #21 is the better fix. This would just be a temporary fix until that gets in :) not sure on the timeline for #21 - if it's coming up, this one can be ignored.

**Comment by stgeke** [comment]
Can you create an issue for this instead of this PR.

**Comment by stgeke** [comment]
Fixed with #183

**Pull request closed without merging**
